### ISSUE TITLE
[D4.3] Implement Owner-Specific Features on NFT Detail Page

### ISSUE THREAD

**Issue by yripper** [joaquinsoza/stellar-tools#20]
**Description:** On the NFT detail page, if the connected wallet is the owner of the NFT, display different marketplaces where the NFT can be listed.

**Tasks:**
- [ ] Check ownership of the NFT based on the connected wallet.
- [ ] Design and implement UI elements to show marketplace options for NFT listing.
- [ ] Ensure seamless navigation to these marketplaces.
