### ISSUE TITLE
[D5.2] Adapt Deflationary Token Contract to Rust for Soroban

### ISSUE THREAD

**Issue by joaquinsoza** [joaquinsoza/stellar-tools#27]
**Description:** Translate the identified Solidity smart contract for deflationary tokens into Rust for deployment on Soroban.

**Tasks:**
- [x] Translate the Solidity contract code to Rust.
- [x] Ensure all key functionalities of the deflationary token are retained.
- [x] Write tests for the Rust-based contract.
- [x] Deploy the contract on the Soroban testnet.
